ann_benchmarks.py, plot.py
Erik,
Thanks for making the benchmark available.  I realized that the installation of KGraph is the most complicated one and I'll make it my next goal to simplify the installation process.
I've made the following changes to your code:
- Switched matplotlib backend to Agg so we no longer need X to plot.
- Specified a universal set of indexing parameters for KGraph.  I've also updated KGraph default parameters to match these.
- Only query parameter P needs to be changed to produce the curve.
Best regards,
- Wei Dong
=> removed X dependency for plot; KGraph parameters.

ann_benchmarks/__init__.py
Hi Erik,
here there are 2 small changes to solve the #23 , hope it fits you. I have also added the normalization of the data for the angular distance, as it is in other libraries, but not sure if this applies for Nearpy. 
cheers
=> Solving #23

ann_benchmarks/__init__.py, install/kgraph.sh
- A command line argument "--algo" is added so one can run only one algorithm instead of all.
- Updated kgraph configuration for two dataset separately.
=> Updated kgraph parameters and etc

ann_benchmarks/main.py, install/nmslib.sh
1. Switching to a Python-thread-enabled NMSLIB version
2. Resolving a merge conflict.
=> Python-thread-enabled NMSLIB version.

.travis.yml, algos.yaml, ann_benchmarks/algorithms/pynndescent.py, install/Dockerfile.pynndescent
Here is a first pass at adding [pynndescent](https://github.com/lmcinnes/pynndescent) to the benchmarks. The implementation is still pretty young, and I'm still working to get a feel for parameter choices, however this should perform adequately, at least for python implementation. I will likely need to update the parameter choice options in algos.yaml in the future to tune things.
=> Pynndescent

.travis.yml, ann_benchmarks/main.py, install.py, install/Dockerfile.faiss, plot.py
Noticed FAISS failed building. At least 3 commands didn't care (building the image, running the algos, plotting). See https://travis-ci.org/erikbern/ann-benchmarks/jobs/376353927
This PR makes sure we raise exceptions in all 3 of those places in the case of failures.
=> Catch failures for various things a bit more

README.md, algos.yaml, ann_benchmarks/algorithms/panng_ngt.py, install/Dockerfile.ngt
We have added our PANNG of NGT library to the benchmarks.
The PANNG is a combination of a graph-based and tree-based indexes.
=> Add PANNG(NGT)

ann_benchmarks/algorithms/base.py, ann_benchmarks/algorithms/dolphinnpy.py, ann_benchmarks/algorithms/dummy_algo.py, ann_benchmarks/algorithms/faiss.py, ann_benchmarks/algorithms/faiss_gpu.py, ann_benchmarks/algorithms/faiss_hnsw.py, ann_benchmarks/algorithms/kgraph.py, ann_benchmarks/algorithms/pynndescent.py, ann_benchmarks/runner.py
This should simplify benchmarks
=> remove use_threads/force_single and cpu affinity, limit CPU using docker

ann_benchmarks/algorithms/onng_ngt.py, install/Dockerfile.ngt
I have improved ONNG to reduce the build times for GIST and NYTimes. To use the improved ONNG, a parameter is needed for the build.
Thank you in advance.
=> update ONNG to reduce the build time

algos.yaml, ann_benchmarks/algorithms/onng_ngt.py
I adjusted a value of the ONNG’s parameter for the latest ONNG version (v1.6.2).
Thank you in advance.
=> update onng parameter

.gitignore, ann_benchmarks/algorithms/annoy.py, ann_benchmarks/algorithms/base.py, ann_benchmarks/algorithms/bruteforce.py, ann_benchmarks/algorithms/definitions.py, ann_benchmarks/algorithms/dolphinnpy.py, ann_benchmarks/algorithms/dummy_algo.py, ann_benchmarks/algorithms/faiss.py, ann_benchmarks/algorithms/faiss_gpu.py, ann_benchmarks/algorithms/flann.py, ann_benchmarks/algorithms/hnswlib.py, ann_benchmarks/algorithms/lshf.py, ann_benchmarks/algorithms/mrpt.py, ann_benchmarks/algorithms/nmslib.py, ann_benchmarks/algorithms/onng_ngt.py, ann_benchmarks/algorithms/panng_ngt.py, ann_benchmarks/algorithms/pynndescent.py, ann_benchmarks/data.py, ann_benchmarks/datasets.py, ann_benchmarks/distance.py, ann_benchmarks/main.py, ann_benchmarks/plotting/metrics.py, ann_benchmarks/plotting/utils.py, ann_benchmarks/results.py, ann_benchmarks/runner.py, create_website.py, install.py, plot.py, test/test-metrics.py
This PR cleans up more flake8 issues: 
```
(py3) $ git branch 
* further-flake8-issues-fixes
master
(py3) $ flake8 . |wc -l 
43
(py3) $ git checkout master
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
(py3) $ flake8 . |wc -l 
248 
```
=> [MRG] Fix more flake8 issues

ann_benchmarks/main.py
This time it's not an accidental PR ;)
=> Fix logic inversion after linting changes

.travis.yml, algos.yaml, ann_benchmarks/algorithms/sptag.py, install/Dockerfile.sptag
SPTAG: https://github.com/microsoft/SPTAG
=> add SPTAG algorithm

algos.yaml
I updated ONNG parameters for the latest version of NGT. I am going to submit another pull request of results with the latest version soon after this pull request.
=> update onng parameters

.travis.yml, README.md, algos.yaml, ann_benchmarks/algorithms/puffinn.py, install/Dockerfile.puffinn
https://github.com/puffinn/puffinn
PUFFINN is an LSH-based ann implementation with support for cosine/jaccard similarity.
Since it doesn't support general Euclidean space, I didn't know what to add to the travis file. (Running it on glove-100-angular would take potentially long.)
=> Added PUFFINN

README.md
#128 pointed out an outdated link which is updated via this PR.
=> Updated link to paper

ann_benchmarks/main.py, ann_benchmarks/runner.py
Signed-off-by: Nicky <nicky.xj.lin@gmail.com>
=> specify cpu for each test-case(single querys mode)

ann_benchmarks/algorithms/milvus.py
Milvus provide a parameter named "ids" on the **insert** function that helps somebody want to specify id for every vector. This will be better than create an additional mapping.
=> Improve milvus.py

install/Dockerfile
should fix #160 (and part of #104)
=> fix ubuntu version

.travis.yml, algos.yaml, ann_benchmarks/algorithms/milvus.py, install/Dockerfile.milvus
A bit janky, since
(a) Milvus is a server process, so I hacked a hacky entrypoint file to run a daemon
(b) was impossible building it from source, but I realized I can just copy the relevant binaries from the "official" dockerfile and it seems to work
Running some benchmarks now, will see what we get
=> Attempt at adding Milvus

ann_benchmarks/main.py, ann_benchmarks/runner.py
This should do the trick :)
Running it on MNIST right now to see if it works
=> make it possible to run multiple containers in parallel

algos.yaml, ann_benchmarks/algorithms/onng_ngt.py
The parameters will probably improve the ONNG result for the last.fm dataset.
=> add ONNG parameters for the last.fm

ann_benchmarks/algorithms/scann.py, install/Dockerfile.scann
See https://github.com/google-research/google-research/commit/b663c6904f4f3800a8fe9766e60c9aba8429dffc for update.
=> Update Dockerfile and Python wrapper for ScaNN 1.1.0

install/Dockerfile.faiss
Faiss changed build system to Cmake instead of configure, and current dockerfile doesn't work
=> Update faiss dockerfile

algos.yaml
=> Unpack HNSW parameters correctly for hamming distance.

install/Dockerfile.milvus, install/Dockerfile.pynndescent
minor workarounds to the docker files
=> Dockerfile updates. Closes #191

install.py
Should resolve current build problems
=> Fix build error

install/Dockerfile.pynndescent
This seems to resolve the current build error
=> fix pynndescent

ann_benchmarks/results.py, plot.py
going forward all results will be stored with a proper extension `.hdf5`
=> simplify filename code and remove spurious warning

ann_benchmarks/results.py
i was a bit too eager to remove code, see https://github.com/erikbern/ann-benchmarks/commit/cc5d20afa0167bf2000def219f826e18e5eb7184
=> fix back separation between batch and non batch

ann_benchmarks/runner.py, create_website.py, plot.py
This documents the arguments taken by `run_algorithm.py` and adds a big notice to the `--help` saying the user probably wants to run `run.py` instead.
=> Added documentation in run_algorithm.py

plot.py
For https://github.com/erikbern/ann-benchmarks/issues/209
=> More scales for plotting

README.md
see https://github.com/erikbern/ann-benchmarks/pull/233#issuecomment-840874010
=> Include Github Actions status in the README

algos.yaml, ann_benchmarks/algorithms/onng_ngt.py, ann_benchmarks/algorithms/qg_ngt.py
Sorry for the confusion. This PR is the same as #221 except for our results.
=> Update parameters for ONNG and QG

install/Dockerfile.sptag
I'm on an M1 mac and I realized almost nothing works because of weird Docker issues, so I'm not able to test it. Hopefully this works.
=> try to fix sptag

.github/workflows/benchmarks.yml, README.md, algos.yaml, ann_benchmarks/algorithms/vald.py, install/Dockerfile.vald
https://github.com/vdaas/vald
Vald is a highly scalable distributed fast ann search engine.
[NGT](https://github.com/yahoojapan/NGT) is used as the core engine.
=> Add Vald to ann-benchmarks

ann_benchmarks/plotting/metrics.py
Hi Maintainers of this repo,
Thank you very much for your excellent work,
I am new to this repository.
I am a researcher studying the best practices of evolving data science codes. According to our findings after examining 1000 data science repositories, migration of loop-based calculations is a widespread evolution practice among developers since it improves performance and code quality. I noticed in this PR's code that it might make better use of NumPy functions and avoid unnecessary loops.
This PR is a minor contribution compared to all the hard work that you have done in this repo. However, I am hoping that it will enhance code quality and, hopefully, performance.
=> Utilize NumPy APIs to remove inefficient Python loops

ann_benchmarks/algorithms/vald.py
This PR will solve vald benchmark failure.
=> fix vald benchmark failure

algos.yaml, ann_benchmarks/algorithms/vald.py, install/Dockerfile.vald
=> use latest Vald version

README.md, algos.yaml, ann_benchmarks/algorithms/milvus.py, install/Dockerfile.milvus
update milvus's version 
Signed-off-by: ting.wang@zilliz.com
=> update milvus's version

.github/workflows/benchmarks.yml, algos.yaml
See https://github.com/erikbern/ann-benchmarks/issues/335
=> Disable a few algos

install/Dockerfile.qdrant
I believe this should resolve it.
=> Fix qdrant

.github/workflows/benchmarks.yml
=> don't run CI twice for every PR

install/Dockerfile.milvus
may or may not fix it, i'm on an M1 so I'm not 100%
=> Fix Milvus?

.github/workflows/benchmarks.yml, algos.yaml, ann_benchmarks/algorithms/pgvector.py, install/Dockerfile.pgvector
super basic pgvector benchmarks – could probably be improved!
=> pgvector support

ann_benchmarks/algorithms/bruteforce.py, ann_benchmarks/datasets.py, ann_benchmarks/distance.py, test/test-distance.py
This should fix the jaccard & hamming benchmarks
=> numpy.bool -> numpy.bool_

.github/workflows/benchmarks.yml, algos.yaml, install/Dockerfile.flann, install/Dockerfile.milvus
kgraph has no activity for more than 3 years, so i think it's a dead project
=> maybe fix milvus & flann, disable kgraph

ann_benchmarks/distance.py, test/distance_test.py
Extra sanity check to prevent the issues we just had in #367 
Thanks @wpjiang for pointing out the issue!
=> angular distance: check consistency with datasets

.github/workflows/benchmarks.yml, algos.yaml, ann_benchmarks/algorithms/redisearch.py, install/Dockerfile.redisearch
Basically just adopted from https://github.com/RedisAI/ann-benchmarks/tree/multiclient_tool
=> Redisearch

.github/workflows/benchmarks.yml, algos.yaml, ann_benchmarks/algorithms/weaviate.py, install/Dockerfile.weaviate
I'm only using `efConstruction` as a parameter here – maybe there's other things we can change too? I couldn't find any docs about what you can change at query time
=> Basic Weaviate implementation

.github/workflows/benchmarks.yml, algos.yaml, ann_benchmarks/algorithms/fast_pq.py, install/Dockerfile.fast_pq
Adds https://github.com/thomasahle/fast_pq to AnnBenchmarks
=> Added FastPQ

algos.yaml, ann_benchmarks/algorithms/weaviate.py
Just parameter changes – it brings the parameters closer to what the other HNSW-based libraries are doing
=> Updates to Weaviate

ann_benchmarks/algorithms/redisearch.py, ann_benchmarks/main.py, ann_benchmarks/runner.py
Dumb error, I was using `X.shape[0]` where it should have been `X.shape[1]`
=> Fix redisearch

algos.yaml, ann_benchmarks/algorithms/weaviate.py, install/Dockerfile.weaviate
* Store id as id (treat uuid as 128bit int)
* upgrade server and client version
* install optional `grpc` client 
* Ran a minimal example with one set of build params locally and all worked fine
=> Adjust Weaviate settings

.github/workflows/benchmarks.yml, algos.yaml, ann_benchmarks/algorithms/tinyknn.py, install/Dockerfile.fast_pq, install/Dockerfile.tinyknn
=> Renamed fast_pq -> tinyknn

README.md
Hi folks,
I noticed that Weaviate wasn't mentioned in the README. I've included it here!
Thanks
=> Added Weaviate to README

README.md
Resolves https://github.com/erikbern/ann-benchmarks/issues/426
=> Specify exact EC2 instance type in readme

ann_benchmarks/definitions.py
=> fix local mode method instantiation

ann_benchmarks/algorithms/base/Dockerfile
=> Relax the Python version check in `base` Dockerfile

ann_benchmarks/datasets.py
=> Use https for datasets

ann_benchmarks/algorithms/pgvector/Dockerfile, ann_benchmarks/algorithms/pgvector/config.yml, ann_benchmarks/algorithms/pgvector/module.py
=> Use HNSW for pgvector

.github/workflows/benchmarks.yml, README.md, ann_benchmarks/algorithms/pg_embedding/Dockerfile, ann_benchmarks/algorithms/pg_embedding/config.yml, ann_benchmarks/algorithms/pg_embedding/module.py
Hi @erikbern 👋 
Thanks for such an amazing benchmark on various ANNs
[pg_embedding](https://github.com/neondatabase/pg_embedding) is an open-source extension for vector search in Postgres that uses HNSW index.
`python install.py` result
```
{'pg_embedding': 'success'}
```
We would love to add pg_embedding to your benchmark!
=> add pg_embedding algorithm

.github/workflows/benchmarks.yml, ann_benchmarks/algorithms/voyager/Dockerfile, ann_benchmarks/algorithms/voyager/config.yml, ann_benchmarks/algorithms/voyager/module.py
Based on hnswlib since voyager is based on it.
CC @psobot @dylanrb123 @markkohdev since they are the primary maintainers of [voyager](https://github.com/spotify/voyager).
=> Add voyager to algorithms

.github/workflows/benchmarks.yml, README.md, ann_benchmarks/algorithms/pgvecto_rs/Dockerfile, ann_benchmarks/algorithms/pgvecto_rs/config.yml, ann_benchmarks/algorithms/pgvecto_rs/module.py
This PR adds [pgvecto.rs](https://github.com/tensorchord/pgvecto.rs), a vector search extension for Postgres.
=> add benchmark for pgvecto.rs

requirements.txt
https://github.com/erikbern/ann-benchmarks/issues/524
docker-py is affected by requests==2.32.x https://github.com/docker/docker-py/issues/3256
This is a temporary measure. Once the compatibility issue is resolved, we can update requests to a more recent version or remove the version pin if appropriate.
=> Update requirements.txt requests==2.31.0

.github/workflows/benchmarks.yml, README.md, ann_benchmarks/algorithms/kgn/Dockerfile, ann_benchmarks/algorithms/kgn/config.yml, ann_benchmarks/algorithms/kgn/module.py
=> add kgn algorithm

ann_benchmarks/datasets.py
This resolves https://github.com/erikbern/ann-benchmarks/issues/560
=> Fix downloads
