ann_benchmarks.py

I fixed a bug in NearPy cosine similarity, updated it on pypi to 0.2.1. 
I also added multi-hash configuration to the NearPy benchmark, because this is the only way I ever use it, hope that is valid with respect to the benchmark.

Added NearPy multi-hash configuration and optimized parameters a bit

---

ann_benchmarks.py

I changed two things in NearPy. The really awful thing was, that no UniqueFilter was used by default. That caused the same indexed vector to be multiple times in the search candidate set. After computing the distance to the query vector and sorting with respect to that, in many cases this caused the cropped N=10 nearest neighbour set to contain the same vector multiple times. Also distance computation was more expensive because of the duplicates. The other thing is that I now store normalized vectors in the index which speeds up distance computation a lot. 
Both changes are released via pypi in NearPy 0.2.2
I also ran your benchmark code with a reduced dataset to look for good parameters. 
This example with just 50000 vectors shows that the above fixes helped a lot so far. Especially the …

New NearPy configurations, after fixing stuff in NearPy

---

README.rst
ann_benchmarks.py
install.sh
install/glove.sh
install/nmslib.sh

Hi, please, consider the following pull request:
* SW-graph is a proximity graph implementation.
* MPLSH (multiprobe LSH). It is actually a ported implementation from LSHKit, which was written by Wei Dong (the kgraph guy :). Yet, it "sits" inside the Non-Metric Space Library and can be invoked like any other supported method. It works only for L2. I tried to use it for the cosine similarity/angular distance knn, but performance wasn't good.
* Ball-Tree (VP-tree) is a ball tree that can adjust its pruning algorithm. This works decently for many metric and **non-metric** spaces. It keeps its own copy of each bucket (see my comments below on cache misses).
* Two variants of the brute-force search: the variant **bruteforce1** copies all vectors to store them in a contiguous chunk of memory. …

Adding benchmarks for some of the Non-Metric Space Library Methods

---

install/glove.sh

GloVe datasets got moved, this is a fix to download them from the right place.

adjust glove.sh to the new URLs for the GloVe datasets

---

ann_benchmarks/__init__.py

Since parsing glove.txt takes lots of memory, it should be done in a separate subprocess so that this memory is getting consistently released.

getting a dataset in a separate subprocess

---

ann_benchmarks/__init__.py
install.sh
install/falconn.sh

I've added FALCONN (http://falconn-lib.org/) tuned for the GloVe dataset.
Here are the results for GloVe on the dedicated c4.2xlarge instance: https://gitlab.com/ilyaraz/experiments/blob/master/glove_results/ec2_flat.txt (other numbers are taken from the upstream of ann-benchmarks).
Here is the comparison of Annoy vs. FALCONN in one point *on the same instance* (to make sure that the numbers from the above make sense): http://pastebin.com/gpDVFQhm

Adding FALCONN

---

install/nmslib.sh
install/sift.sh

I have retested NMSLIB using the updated version (which downloads v1.5). Seems to be fine. If you were waiting for an updated version to run SIFT benchmarks, you can run them now. Even faster with saved indices. We don't cheat and don't save answers there :-) Only the indices themselves.
Additionally, I changed the source location of convert_texmex_fvec.py (to be from NMSLIB v1.5 too). I sometimes rename folders, it's not a good idea to pull it from master. Really, on a second thought: ann_benchmark could probably keep its own copy of convert_texmex_fvec.py.

Using NMSLIB code from a release rather than from an obscure branch

---

ann_benchmarks/__init__.py
install/kgraph.sh

- Fixed KGraph performance issue (substantial changes to pykgraph implementation to remove the per-batch query overhead, which cannot be amortized with evaluated with batch-size 1).
- Allow saving and reusing KGraph index. 
- Caching train test data to speedup evaluation.

fixed kgraph, caching train/test data

---

ann_benchmarks/main.py
install.sh
install/faiss.sh

This adds basic support for faiss on the cpu as suggested in https://github.com/erikbern/ann-benchmarks/issues/34. The timing results on my system seem to be on par with Annoy on the glove dataset:

Add support for Faiss

---

README.md
ann_benchmarks/datasets.py

This pull request adds support for the NYtimes dataset.  The NYTimes bag-of-words dataset is transformed into a 256 dimensional real-valued value by normalizing the word occurrences matrix using tfidf and then projecting done to 256 dimensions.
The bag-of-words transformation is kept general, since it potentially generalizes to other datasets.

NYtimes dataset

---

ann_benchmarks/algorithms/nmslib.py

Nice work on all the recent changes! I saw your post this morning and decided play around with this again.
One thing I noticed was that this package is using an old version of the nmslib api. While I kept that version around for backwards compatibility, the newer version has a couple of advantages: you don't
need to call freeIndex, the newer version accepts numpy arrays as inputs etc etc.
Also, I think you are running into this issue https://github.com/searchivarius/nmslib/issues/291 . I noticed that the tests hung here, but when switching the Dockerfile.nmslib to point to my repo of nmslib (with the fix) it worked.

Upgrade to use newer NMSLIB api

---

ann_benchmarks/algorithms/definitions.py
ann_benchmarks/main.py
install/Dockerfile.faiss
install/Dockerfile.kgraph
install/Dockerfile.nmslib
install/Dockerfile.panns

Here's a minor fix for local mode that lets the framework skip over missing algorithms. (Commit 70836ecca6c6649fe91dc678ea1b790b682cde42 added this, but only for Docker mode.)

Skip missing algorithms in local mode

---

.travis.yml
ann_benchmarks/plotting/metrics.py
ann_benchmarks/plotting/utils.py
ann_benchmarks/results.py
ann_benchmarks/runner.py
create_website.py
install.py
plot.py
requirements.txt
templates/chartjs.template
templates/detail_page.html
templates/general.html
templates/latex.template
templates/summary.html
test/test-metrics.py

This PR adds back support for running `createwebsite.py`. This script builds a website containing interactive plots for all results that are stored. Enabling support for this resulted in some questionable choices after #54. In particular, 
- Needed to add auxiliary helpers to load all the results. It's not a lot of code, but it seems hard to maintain with other parts of code such as `get_result_filename`.
- Needed to convert a lot of data, because the plotting utils now always assume an `x` and `y` value; however, generating all the plots uses a dict from which we can read of the `x` and `y` values. This is really going to hurt performance of the script for large result repositories.
In general, `create_website.py` is a monolithic beast because of all the html output that is stored …

Bring back create_website.py

---

create_website.py

#57 unfortunately had a bug where the dictionary that belongs to a distance measure was added more than once due to an incorrect indentation. This PR fixes that.

Fix dataset overview on summary page in create_website.py.

---

ann_benchmarks/datasets.py

Think this should basically work
Closing #68

Use word2bits to create a Hamming dataset

---

.travis.yml
algos.yaml
ann_benchmarks/algorithms/definitions.py
ann_benchmarks/main.py
ann_benchmarks/runner.py

Keep the unit tests for now, just don't run them by default (unless you pass the `--run-disabled` flag)

disable panns, nearpy, faiss-lsh, dolphinn

---

install.py

- Add `--proc` option for setting multiprocessing pool to build docker
images faster
- Add `--algorithm` option seeming like `LIBRARY` environment
- Remain `LIBRARY` env option but `--algorithm` option has higher priority

Add multiprocessing for building multiple docker images simultaneously

---

install/Dockerfile.faiss

Seems like Faiss has been a bit flaky lately in Travis, and I see it's failing because swig is missing. No idea why it works sometimes.

install swig for faiss

---

.travis.yml
README.md
algos.yaml
ann_benchmarks/algorithms/base.py
ann_benchmarks/algorithms/definitions.py
ann_benchmarks/algorithms/faiss.py
ann_benchmarks/algorithms/faiss_gpu.py
ann_benchmarks/algorithms/faiss_hnsw.py
ann_benchmarks/algorithms/nmslib.py
ann_benchmarks/main.py
ann_benchmarks/results.py
ann_benchmarks/runner.py
create_website.py
plot.py
templates/detail_page.html
templates/summary.html

This PR improves the rudimentary support for batch mode that is already present in ann-benchmarks. Batch mode is enabled by providing `--batch` to `run.py`. Runs in non-batch/batch mode are treated completely independently by the the plotting scripts. That means `--batch` has to be provided to `plot.py` to plot results for batched runs; the website generated by`create_website.py` has different sections for batched/non-batched queries, where all batched runs have to suffix "-batch".
The approach is pretty straight-forward: There is a method `batch_query(X)` that gets the whole query set at once. The default implementation is to query each individual point with the standard query procedure, but all of faiss' and nmslib's implementations support a dedicated batch method that is used in this …

Support for Batch mode

---

README.md
algos.yaml
ann_benchmarks/algorithms/bruteforce.py
ann_benchmarks/algorithms/nmslib.py
ann_benchmarks/datasets.py
ann_benchmarks/main.py

This PR adds (back) support for bitvectors under Hamming distance. Note that it requires to store the `point_type` within the hdf5 file, so vectors have to be regenerated, @erikbern.
I have added a binary version of the SIFT dataset to it, generated using Spherical hashing. Unfortunately, I don't know of a nice Python implementation of Spherical hashing which would allow producing the binary embedding from SIFT directly from the source (and for other of our datasets as well).
I've tried to add back support for set similarity under Jaccard distance.  Here, each data point is a variable-length set of integers. This turns out to be difficult with the current infrastructure: First, hdf5 doesn't support vectors of `frozenset`s in a straight-forward way. Next, the code becomes really ugly …

Bitvectors and Hamming distance

---

algos.yaml
ann_benchmarks/algorithms/mrpt.py
install/Dockerfile.mrpt

We updated the benchmarking code of MRPT to match a new version of MRPT which has automatic tuning of hyperparameters. This speeds up benchmarking significantly, since there is no need to perform a grid search over 3 hyperparameters anymore.  
The parameters currently used for MRPT are really suboptimal: maximum number of trees 100 and maximum depth is 8, but for larger datasets, such as SIFT and GIST, the optimal number of trees is usually on the range 200-1000, and the optimal depth on the range 8-12. This PR also fixes this.
Now MRPT also works for angular distance (see comments on #83). The problem was in our python bindings.

Add autotuning and update proper parameters for MRPT

---

.travis.yml
ann_benchmarks/algorithms/base.py
ann_benchmarks/algorithms/faiss.py
ann_benchmarks/algorithms/faiss_hnsw.py
ann_benchmarks/plotting/metrics.py
ann_benchmarks/plotting/plot_variants.py
ann_benchmarks/plotting/utils.py
ann_benchmarks/results.py
ann_benchmarks/runner.py
create_website.py
install/Dockerfile.flann
plot.py
test/test-metrics.py

This PR makes the following changes:
- Added mechanism to allow an implementation to report on additional characteristics. This is showcast by having IVF and HNSW (from faiss) report the number of distance computations done to answer the set of queries (which is a general benchmark of the quality more independent than running times).
- Small refactorings in metric computation, report not only on avg but also standard deviation. (To be later added as error bars in plots.)
- Store computed metrics inside the result file to avoid recomputation
- Improved plotting time by a factor ~4 by better caching of hdf5 access and small changes to the metric computation
The general goal of these changes is to make it easier to work with our result files, e.g. for visualization of results beyond those …

Small changes to metrics computation + additional metrics

---

ann_benchmarks/plotting/utils.py

If we have a set of points that have the same Y value, those that are more valuable on X should be first.
The error is most noticeable right now in the Index size-Recall tradeoff graphs where sometimes there are line segments parallel to the recall axis (different recall values having the same index size).

Fix Pareto frontier generation.

---

algos.yaml
ann_benchmarks/algorithms/sptag.py
install/Dockerfile.sptag

As discussed in #119, this PR makes SPTAG use the libboost1.67-dev-all package instead of building boost itself.
libboost-dev-all comes with a Python 2 dependency, which is the preferred Python version in SPTAG's build system. Thus I changed the entry point to run with Python 2.

Updated SPTAG docker file

---

ann_benchmarks/algorithms/faiss_hnsw.py
ann_benchmarks/algorithms/sptag.py

Adds a missing query parameter to the name in the result file. Currently we cannot say which query parameter gave a particular data point.

Fix naming of Faiss' HNSW and SPTAG.

---

.travis.yml
README.md
algos.yaml
ann_benchmarks/algorithms/datasketch.py
ann_benchmarks/algorithms/puffinn.py
ann_benchmarks/datasets.py
ann_benchmarks/distance.py
ann_benchmarks/runner.py
test/test-jaccard.py

This PR reintroduces support for ANN for sets under Jaccard similarity. (It always bothered me that we lost support for a 1k star ANN implementation https://github.com/ekzhu/datasketch/.) Currently, there is only one standard data set and some random sets for testing.
I tried to keep the PR as minimally invasive as possible. This means that sets are stored as bit vector representation in hdf5 (because they are supposed to be 2d np matrices), but are then transformed to a sparse list-of-indices representation (needed by the algorithms).
Looking forward to hearing your thoughts!

Reintroduce Set Similarity under Jaccard Distance

---

algos.yaml
ann_benchmarks/algorithms/pynndescent.py
install/Dockerfile.pynndescent

It seems like pynndescent was broken (or otherwise drastically underperforming) in the last round. I've updated pynndescent, and pushed a new version to PyPI. This PR should update ann-benchmarks to use the new version (with it's changed parameters), and now only pull from PyPI (rather than master on the github repository) so it should be more stable in future.

Pynndescent update

---

ann_benchmarks/algorithms/pynndescent.py
install/Dockerfile.pynndescent

Pynndescent supports jaccard distances on datasets like kosarak via the scipy sparse matrix format. This updates the pynndescent algorithm wrapper to convert data into the requisite sparse format when using jaccard. I also pinned the numba and llvmlite versions as the current release combinations have some issues that break pynndescent.

Support for jaccard with pynndescent

---

README.md
ann_benchmarks/datasets.py

This commit adds an image similarity dataset based on the data from 'Efficient
Indexing of Billion-Scale datasets of deep descriptors'. The data is composed of
images from the web that have been run through a 'deep descriptor network' to
produce vectors. The vectors were then reduced to 96 dimensions through PCA and
finally L2-normalized. We use a 10 million vector sample of the full dataset.
The original dataset can be downloaded from
http://sites.skoltech.ru/compvision/noimi/. The 10 million vectors are taken from
the file deep10M.fvecs. I emailed the authors of the dataset (with @erikbern in CC)
and they're okay with us committing a sample of the dataset.
Closes #143.

Add an dataset based on 'deep image descriptors'.

---

.gitignore
.travis.yml
algos.yaml
ann_benchmarks/algorithms/elasticsearch.py
install/Dockerfile.elasticsearch

Brute force queries using vanilla elasticsearch.
Uses the [dense_vector field type](https://www.elastic.co/guide/en/elasticsearch/reference/master/dense-vector.html) to store vectors and [script_score queries for searching](https://www.elastic.co/guide/en/elasticsearch/reference/master/query-dsl-script-score-query.html).
It's quite slow. So far it looks like fashion-mnist is taking ~400ms per query on my i7-8750H.
ES also has a sparse_vector datatype, but it will be deprecated in 8.0.

Elasticsearch with dense_vector field type and script_score query

---

install/Dockerfile
install/Dockerfile.pynndescent

Tested on a fresh GCP Compute Engine VM running Ubuntu 18.04. 
Had to install `gcc` and `docker` first though.

fixes #190. Ubuntu 18.04 fix.

---

ann_benchmarks/plotting/utils.py
install.py

This PR addresses 2 things:
1. The colors in the plot are made slightly darker as reported in #194 
2. Individual algorithms that error while installing will not stop the installation of other algorithms. Instead, we will install whatever algorithm does install and print the install status of all algorithms at the end.

closes #194. Also adds some resilience to failing packages

---

ann_benchmarks/algorithms/definitions.py
ann_benchmarks/results.py
ann_benchmarks/runner.py
create_website.py
plot.py
templates/summary.html

my previous attempts to simplify the results code wrt batching introduced a bunch of issues that i guess i could have reverted, but instead i decided to keep digging a bit and i think i was able to simplify it even further and get things working again
1. batching is no longer a part of any algorithm name, just the filename
2. we do no longer infer whether batching is used from the filename, but instead read it from the result metadata
i think it's a bit cleaner

simplify the batch stuff further

---

.travis.yml
README.md
algos.yaml
ann_benchmarks/algorithms/opendistro_knn.py
ann_benchmarks/algorithms/opendistroknn.py
install/Dockerfile.opendistroknn

Adding Open Distro Elasticsearch KNN plugin support by borrowing on the ES setup from `elasticsearch` and `elastiknn`. Below is a comparison on `fashion-mnist` between this `opendistroknn` and `elastiknn`, where `opnedistroknn` has ~3X better queries/s at comparable recall.

Adds Open Distro Elastic Search's KNN plugin support. Closes #174.

---

plot.py

Removing call to `get_algorithm_name` function that was removed in a previous PR

Fix plot.py error when -o is not specified

---

install/Dockerfile.opendistroknn

Fixing breaking changes in opendistro 1.12.0 installation. This should fix the broken build.

updating opendistro for opendisto 1.12.0

---

ann_benchmarks/algorithms/base.py
ann_benchmarks/main.py
create_website.py

A follow-up on #201. I think the batch mode file handling works nicely again (except #203). 
However, the whole docker parallelization rendered batch mode in Docker useless and this PR fixes this. Batch mode was meant to allow an implementation to go 'all in' with CPU/GPU resources. It doesn't help an implementation much if it receives all the queries at once if it then has to solve it in a single thread :-) 
I tried to find a fix that was minimally invasive with the rest of the code base. Let me know what you think.

Fix batch mode behavior

---

README.md
algos.yaml
ann_benchmarks/algorithms/qg_ngt.py

Thank you for your time and effort to provide and maintain your awesome benchmarks.
We have implemented a quantized graph into [NGT](https://github.com/yahoojapan/NGT). I'd like you to merge the NGT-QG PR including a bug fix of ONNG to your ann benchmarks. The followings are its results (glove-100 and shift-128) on the AWS c5.4xlarge instance. Unfortunately, it takes about 3.5 hours that is longer than the default timeout [2 hours](https://github.com/erikbern/ann-benchmarks/blob/master/ann_benchmarks/main.py#L97) to produce the result of glove-100. I wish I could use multiple cores to build the indexes.

add NGT-QG

---

install/Dockerfile.faiss

All FAISS implementations turned out pretty slow in the last benchmark run. This PR fixes that.

Updated faiss docker file

---

install/Dockerfile.milvus

Build milvus by `python install.py --algorithm milvus ` repeatedly will be failed, because that  docker sees the initial and modified instructions as identical and reuses the cache from previous steps. As a result the apt-get update is not executed because the build uses the cached version. Because the apt-get update is not run.
For details, please refer to this article: https://docs.docker.com/develop/develop-images/dockerfile_best-practices/

Fix install milvus failed.

---

ann_benchmarks/runner.py

7d767f53210981fac8fe2bfb559ce1410b1a1af0 sneaked in a bug so that it doesn't stop containers after running into a timeout. This had the nice effect that some containers would later share the CPU with a container that was supposed to be killed.

Stop container after timeout.

---

.travis.yml
README.md
algos.yaml
ann_benchmarks/algorithms/diskann.py
install/Dockerfile
install/Dockerfile.diskann
install/Dockerfile.diskann_pq

Hey @erikbern and team,
We've added the support for Vamana and Vamana-PQ in-memory indices (from the [DiskANN paper](https://proceedings.neurips.cc/paper/2019/hash/09853c7fb1d3f8ee67a61b6bf4a7f8e6-Abstract.html)) to your amazing repository. Correspondingly, we've run a few comparison experiments with some other top algorithms on our Azure VM (Intel(R) Xeon(R) Platinum 8272CL CPU + 128 GB RAM). Both the variants seem to offer competitive performance under different settings.

Add Vamana and Vamana-PQ (DiskANN) to ANN Benchmarks

---

create_website.py

When generating batch results, the "batch" suffix was repeatedly added, resulting in the file not being found on the web page.
After fixed:

Fix creating 'Benchmarks for Batched Queries' website.

---

.github/workflows/benchmarks.yml

Hi,
Since TravisCi for Organizations will shut down in the next few weeks, I thought it would be better to move to Github Actions.
There are a few failures, but I suppose that's similar as when using TravisCI.
What do you think?

Migrate from Travis to Github Actions

---

ann_benchmarks/algorithms/puffinn.py

It seems the dimensions passed to PUFFINN was broken when using Jaccard similarity measure (I couldn't execute it on kosarak).
Here is some partial results (executed on my computer for now) for the Jaccard similarity on the Kosarak dataset.
Would you be interested in having other datasets for jaccard similarity ?
I also believe it would be interesting to differenciate the way datasets are stored for jaccard vs other measures as currently it is quite (no sparse representation).

Fix puffinn algorithm for jaccard similarity measure

---

README.md
ann_benchmarks/datasets.py
ann_benchmarks/distance.py
ann_benchmarks/main.py
ann_benchmarks/runner.py
create_website.py
plot.py

Following @maumueller's comment in https://github.com/erikbern/ann-benchmarks/pull/234#issuecomment-836243852, here is an implementation of sparse datasets to be closer to jaccard similarity requirements.
Note however that this change is not backward compatible for the kosarak dataset.
Is it a no go and should I add some backward compatibility layers?

Use sparse datasets for jaccard similarity

---

.github/workflows/benchmarks.yml
ann_benchmarks/algorithms/puffinn.py
ann_benchmarks/distance.py
test/test-jaccard.py

Sorry my two PRs (https://github.com/erikbern/ann-benchmarks/pull/235 and https://github.com/erikbern/ann-benchmarks/pull/234) were not compatible with each other, I should have added a note.
So here's a fix, and I added puffinn with jaccard to the tests set to make it easier to detect in the future.

Make Puffinn algorithm compatible with sparse dataset format

---

.github/workflows/benchmarks.yml
README.md
algos.yaml
ann_benchmarks/algorithms/vespa.py
install/Dockerfile.vespa

[Vespa](https://vespa.ai/) is an open source big data serving engine that supports approximate nearest neighbor search by using an in-memory HNSW index. Vespa implements a modified version of the Hierarchical Navigable Small World (HNSW) graphs algorithm ([paper](https://arxiv.org/abs/1603.09320)). The Vespa implementation supports:
- Combining HNSW lookups with metadata filters and text search
- Real-time index updates
- Multi-threaded indexing and searching
For more details see [Approximate Nearest Neighbor Search using HNSW Index](https://docs.vespa.ai/en/approximate-nn-hnsw.html).
This integration adds benchmarking directly towards the Vespa HNSW index and experiments show comparable performance with other HNSW algorithms. The Vespa HNSW index has less co-localisation of data in …

Add Vespa HNSW to ANN Benchmarks

---

ann_benchmarks/datasets.py

Looking at #250 I noticed the following bug that would occur when running on new datasets: 
```
$ python3 run.py --dataset mnist-784-euclidean --algorithm annoy
Traceback (most recent call last):
File "run.py", line 6, in <module>
main()
File "/home/maau/ann-benchmarks/ann_benchmarks/main.py", line 159, in main
fn = get_result_filename(args.dataset,
File "/home/maau/ann-benchmarks/ann_benchmarks/results.py", line 20, in get_result_filename
d.append(re.sub(r'\W+', '_', json.dumps(data, sort_keys=True))
File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
return cls(
File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
chunks = self.iterencode(o, _one_shot=True)
File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
return _iterencode(o, 0)
File …
```

Fixed using @dimension in yaml file 

---

install/Dockerfile.scann

Replcing build from source build method with pip install for scann. Current Dockerfile for Scann was building SCANN from source by building a whl file which can fail due to errors like =>
```
E: Failed to fetch https://storage.googleapis.com/bazel-apt/dists/stable/InRelease  403  Forbidden [IP: 199.36.153.4 443]
E: The repository 'https://storage.googleapis.com/bazel-apt stable InRelease' is not signed.
The command '/bin/sh -c apt-get update && apt-get install -y bazel-3.4.1' returned a non-zero code: 100
```

Replcing build from source build method with pip install for scann

---

.github/workflows/benchmarks.yml
requirements.txt

In an attempt to simplify the installation, let's just use latest ubuntu (20.04) with the default version of Python (3.8)

Ubuntu 20.04 and default python

---

algos.yaml
ann_benchmarks/algorithms/elastiknn.py
install/Dockerfile.elastiknn

Bumps Elastiknn versions to the latest.
Modifies algo parameters such that we can remove a data scaling step which was previously required in order to get decent results. The main difference is the width param, w: we set it higher to accommodate for the scale of the vector values, instead of scaling the vectors to accommodate for the w param.
New results should be on-par or better for Fashion MNIST. I haven't tested thoroughly with SIFT yet. I'll run some more tests this week on my own hardware and follow-up with another PR if necessary. Even if the params don't work well for SIFT, the algo will early-stop if throughput is < 50 qps after 500 queries.
New results running on my Dell XPS w/ i7-8750H CPU @ 2.20GHz.

Elastiknn: update to latest release, remove data scaling

---

install/Dockerfile.vespa

With [Vespa 8](https://blog.vespa.ai/vespa-8-is-here/), the [supported OS has changed from CentOS 7 to CentOS Stream 8](https://blog.vespa.ai/Upcoming-changes-in-OS-support-for-Vespa/).

Switch to CentOS Stream 8 as OS for vespa container.

---

.github/workflows/benchmarks.yml
install.py

* Split the "install dependencies" step to two steps: 1) install project dependencies, 2) build the library image.
* Run `pip install` with `--quiet` to limit logging for faster CI debugging.
* Make install.py return 1 if the installation fails. Without this, the CI failures are misleading: install step succeeds even though install failed, then the run step fails w/ a confusing "nothing to run" error.
* Dedup the env vars in the CI workflow. We can have one env block for the full job, rather than the same env vars per step.
* Add concurrency settings to the CI workflow to cancel the workflow for the previous commit when a new commit is pushed.
* Add a timeout-minutes set to 20 to prevent runaway workflows, like the one here: https://github.com/erikbern/ann-benchmarks/pull/328#issuecomment- …

Improvements to CI workflow

---

install/Dockerfile.vespa

This tracks move of xxhash-libs package to the powertools repo which is disabled by default.

Enable powertools repo when installing vespa-ann-benchmark package.

---

ann_benchmarks/algorithms/elastiknn.py
install/Dockerfile.elastiknn

Upgrading elastiknn to the latest version 8.6.2.0.
I had to change the Elasticsearch installation to just use a tar download instead of using apt and deb files. This let me avoid systemd and sysctl, which I couldn't get working with the latest versions of Elasticsearch (even on newer ubuntu containers).
I still have to do a bit of gymnastics to get the python client installed. This should be resolved by upgrading to newer Python.
I had to increase the time spent waiting for Elasticsearch's to become available. It seems to take longer to initialize on 8.x versions compared to 7.x

Upgrade elastiknn to 8.6.2.0

---

.github/workflows/benchmarks.yml
README.md
install/Dockerfile
requirements.txt

Re #316 
* Upgrade the base Docker container to Ubuntu 22.04
* This automatically upgrades Python to 3.10.6
* Upgrade all packages in requirements.txt to their latest versions. I basically just pip-installed them one by one and pegged the requirements file to the version that was installed.

Upgrade to Ubuntu 22.04 and Python 3.10

---

README.md

Leverage https://shields.io/ to create Github stargazer badges next to each evaluated library implementation.
Skip those that are part of bigger projects that don't directly relate to ANN (google-research, scipy, etc.)
While not the most direct metric, it gives some sense of how well-adopted each implementation is.

Add Github stargazer badges

---

install/Dockerfile.vespa

The required python packages cannot be installed when using default python3 on CentOS Stream 8 (Python 3.6.8) but they
can be installed when using Python 3.9.16.

Use Python 3.9 on CentOS Stream 8.

---

.github/workflows/benchmarks.yml
requirements.txt

Hi, thanks for this project!
This updates NumPy and SciPy to the latest version so `pip install -r requirements.txt` works with Python 3.11.

Update numpy and scipy to work with Python 3.11

---

install/Dockerfile.vespa

Docker image for CentOS Stream 8 no longer includes dnf copr plugin.

Install dnf-plugins-core to get dnf copr plugin.

---

ann_benchmarks/distance.py
requirements.txt
test/test-distance.py

wasn't able to install it on my mac, and it's basically not used anyway – it's very easy to just implement these distance metrics using numpy

remove scipy dep

---

.github/workflows/benchmarks.yml

Minor PR to fix the following warning on CI:
"Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2"

Fix CI warning

---

plot.py

Fixes a few warnings generated by:
```sh
python3 plot.py --dataset $DATASET --output plot.png --raw
```
Output
```text
ann-benchmarks/plot.py:35: UserWarning: linestyle is redundantly defined by the 'linestyle' keyword argument and the fmt string "-" (-> linestyle='-'). The keyword argument will take precedence.
(handle,) = plt.plot(
ann-benchmarks/plot.py:40: UserWarning: linestyle is redundantly defined by the 'linestyle' keyword argument and the fmt string "-" (-> linestyle='-'). The keyword argument will take precedence.
(handle2,) = plt.plot(
ann-benchmarks/plot.py:76: MatplotlibDeprecationWarning: The 'b' parameter of grid() has been renamed 'visible' since Matplotlib 3.5; support for the old name will be dropped two minor releases later.
plt.grid(b=True, which="major", …
```

Fix warnings in plot.py

---

algos.yaml
ann_benchmarks/algorithms/pgvector.py
install/Dockerfile.pgvector

Initial round of improvements for pgvector:
1. Set `ivfflat.probes` to improve recall
2. Remove `OPTFLAGS=""` so it's compiled with `-march=native` (which enables additional SIMD instructions on supported platforms)
3. Use Unix-domain socket (rather than networking stack)
4. Use binary serialization (to reduce serialization overhead)
5. Use prepared statements (to reduce statement parsing overhead)
6. Increase `work_mem` (to allow for more memory usage)

pgvector improvements

---

.github/workflows/benchmarks.yml
install/Dockerfile.sptag

SPTAG added a [Git submodule for `zstd`](https://github.com/microsoft/SPTAG/tree/0df1b75e6a75660c13d91b3663671a2159eaea96/ThirdParty), which causes the build to fail with the following error:
```text
CMake Error at CMakeLists.txt:121 (add_subdirectory):
add_subdirectory given source "ThirdParty/zstd/build/cmake" which is not an
existing directory.
```
This PR fixes that error, along with the remaining CI warning.
The build [still fails](https://github.com/ankane/ann-benchmarks/actions/runs/4660508942/jobs/8248650137) with a new error:
```text
In file included from /home/app/SPTAG/AnnService/inc/Core/Common/WorkSpacePool.h:8,
from /home/app/SPTAG/AnnService/inc/Core/BKT/Index.h:15,
from /home/app/SPTAG/AnnService/src/Core/BKT/BKTIndex.cpp:4: …
```

Partial fix for SPTAG build

---

README.md

More info on badge update: https://github.com/badges/shields/issues/8671
Could alternatively use the badge from GitHub Actions:
[![ANN benchmarks](https://github.com/erikbern/ann-benchmarks/actions/workflows/benchmarks.yml/badge.svg)](https://github.com/erikbern/ann-benchmarks/actions/workflows/benchmarks.yml)

Add pgvector to readme and fix build status badge

---

algos.yaml

Fixed git issues.
New values don't grow exponentially, but fast than the first "tier".

More query params for fast_pq

---

algos.yaml
ann_benchmarks/algorithms/fast_pq.py

I talked to Matthijs Douze, and he recommended using a number of clusters that's slightly larger than sqrt(N).
This commit just adds three build arguments to do that.

Added a skew factor to the number of clusters

---

algos.yaml

With always `512`, we risk running into timeouts in some scenarios, let's also consider smaller values.

Weaviate: Add more efConstruction options

---

install/Dockerfile.opensearchknn

It's currently not possible to run the OpenSearch KNN benchmark on arm64 (useful for local debugging and development).
Tweak the Dockerfile to download a architecture specific version of OpenSearch.

Tweak OpenSearch Dockerfile to download architecture specific version

---

README.md
algos.yaml
ann_benchmarks/algorithms/elasticsearch.py
install/Dockerfile.elasticsearch

Add an implementation for [Elasticsearch KNN search](https://www.elastic.co/guide/en/elasticsearch/reference/current/knn-search.html). Fixes https://github.com/erikbern/ann-benchmarks/issues/298.
- Supports specifying [`index_options`](https://www.elastic.co/guide/en/elasticsearch/reference/8.7/dense-vector.html#dense-vector-params) via arg groups, with one entry for Elasticsearch's [default settings](https://www.elastic.co/guide/en/elasticsearch/reference/8.7/dense-vector.html#dense-vector-params) for M and EF.
- Supports specifying [`num_candidates`](https://www.elastic.co/guide/en/elasticsearch/reference/8.7/knn-search-api.html#knn-search-api-request-body) via query args.
What do you think @erikbern, @alexklibisz?

Add Elasticsearch KNN

---

algos.yaml
ann_benchmarks/algorithms/pgvector.py
install/Dockerfile.pgvector

Hi @erikbern, thanks for the updated benchmarks. Made two more improvements to pgvector:
1. Disabled compression and out-of-line storage
2. Set `-mprefer-vector-width=512`
Also, removed `lists = 10000` since it requires `maintenance_work_mem` to be higher.

Improve pgvector performance by ~2x

---

ann_benchmarks/algorithms/opensearchknn/Dockerfile
ann_benchmarks/algorithms/opensearchknn/module.py

Improved the OpenSearchKNN setup. The older setting of OpenSearch K-NN is not optimized for 1 CPU and 1 machine. 
**Changes involve:**
1. Use `_id` to store the id of the vector.
2. Increase the timeouts for force_merge so that force_merge is actually performed.
3. Setup the OpenSearch cluster with min distribution + K-NN plugin to remove all the background activities done by other plugins which are not required for doing vector search and indexing. The change ensure that plugin is added on top of core Opensearch.
5. Updated the warmup to run after the index settings are changed for every query configuration, as warmup is useless if the index setting of ef_search is changed.
6. While doing force_merge I set max segments to 5. This is to make sure that dataset with bigger dimensions can …

Improved OpenSearchKNN setup for doing benchmarks

---

ann_benchmarks/algorithms/qdrant/Dockerfile
ann_benchmarks/algorithms/qdrant/module.py

- bump qdrant to v1.3.0
- bump qdrant-client (python) to v1.3.1
- minor improvements during vector loading
- cleanup dockerfile
References:
https://github.com/qdrant/qdrant/releases/tag/v1.3.0

chore: Version bump qdrant to v1.3.0

---

ann_benchmarks/main.py

Fixes a regression introduced in #431 that led all runs re-run although results are present.

Fix result caching by providing actual dataset name.

---

.github/workflows/benchmarks.yml
README.md
ann_benchmarks/algorithms/nndescent/Dockerfile
ann_benchmarks/algorithms/nndescent/config.yml
ann_benchmarks/algorithms/nndescent/module.py

This adds support for [nndescent](https://github.com/brj0/nndescent), which is a C++ implementation of `pynndescent`.
Although single queries are slower compared to the original Python implementation, the build time (which includes the creation of a k-NN graph for the training data) on my machine shows a significant improvement. Here are the results of `ann-benchmarks` for **fashion-mnist-784-euclidean_10_euclidean**:
Recall  | nndescent | pynndescent
--------|-----------|------------
0.9667  | 13.609    |
0.9693  | 14.184    |
0.9876  | 21.162    |
0.9877  |           |  81.0728
0.9997  | 42.560    | 111.5696
1.0000  | 51.341    | 125.3250

add nndescent algorithm

---

ann_benchmarks/algorithms/pgvector/module.py

The size of the pgvector index comes from data stored in PostgreSQL; its not available in the memory context that the index is built in. This defines an ad hoc "get_memory_usage" function that lets the pgvector test load the size of the created index from the database.

Get correct index size for pgvector

---

ann_benchmarks/datasets.py

The current code generates datasets that are all 1M rows instead of the intended number.
https://stackoverflow.com/questions/6076270/lambda-function-in-list-comprehensions

Fix dbpedia-openai-*k-angular datasets

---

ann_benchmarks/algorithms/qdrant/module.py
ann_benchmarks/definitions.py
ann_benchmarks/runner.py

We should calculate latency for each batch instead of just using the average because it will be more precise. At the moment, all "times" values are the same as the average which really defeats the purpose of p99 and p95 values. 
Plus, I noticed a bug while running with `--batch --local`. All the algorithms have been refactored to have a `module.py` but the runner wasn't updated accordingly which makes it fail when running it locally with batches. To keep the change minimal I just modified `definitions.py` instead of all the config files.
I just did this for Qdrant right now but can do it for others as well once this PR is approved and merged :)
Also, thanks for creating/maintaining this repo. Really great work!

feat: Calculate latency for each batch instead of just using the average for all queries

---

ann_benchmarks/algorithms/annoy/config.yml
ann_benchmarks/algorithms/elastiknn/config.yml
ann_benchmarks/algorithms/kdtree/config.yml
ann_benchmarks/algorithms/nmslib/config.yml
ann_benchmarks/algorithms/onng_ngt/config.yml
ann_benchmarks/algorithms/qdrant/config.yml

These are algos that are either chronically bad or dominated by some other flavor within the same family
Sad to see you go, Annoy, but the time has come

Disable a few algos

---

ann_benchmarks/algorithms/vearch/Dockerfile

This commit addresses potential compatibility issues by explicitly specifying the version of the vearch library as 3.2.8.3 in the Dockerfile. Without version pinning, the lack of a specified version could lead to interface incompatibilities with future updates. By specifying the version, we ensure a stable and known state of the vearch library, reducing the risk of unexpected errors due to incompatible changes in future releases.

Update vearch Dockerfile: pin vearch version to 3.2.8.3 in Dockerfile

---

ann_benchmarks/algorithms/vespa/Dockerfile

This PR switches the container base image to AlmaLinux 8 in order to track the [changes in OS support for Vespa](https://blog.vespa.ai/Changes-in-OS-support-for-Vespa/)

Track change in Vespa OS support (CentOS Stream 8 => AlmaLinux 8).

---

ann_benchmarks/algorithms/pgvector/module.py

Particularly on large vector types, the pgvector module was spending significant time on converting floating point values to ASCII before being transmitted to the PostgreSQL server. This changes keeps the format in binary, reducing overhead. One test demonstrated a 63% reduction in load time, which would have an impact on the overall "build" time as reported by this benchmark.

Update pgvector loading method to use binary format

---

ann_benchmarks/algorithms/pgvector/Dockerfile

Hi, this PR makes two updates to pgvector:
1. Fixes `could not resize shared memory segment` error with pgvector 0.6.0 and Docker by explicitly disabling parallel index builds (`max_parallel_maintenance_workers` change)
2. Updates Postgres from 14 to 16 (which requires the `GRANT` change)

pgvector updates

---

ann_benchmarks/algorithms/faiss_hnsw/config.yml

Fixed an error that occurred when executing in an environment where the docker image for faiss_hnsw existed and the docker image for faiss did not exist.
This will be failed:
```console
$ python install.py --algorithm faiss_hnsw
$ python run.py --algorithm 'hnsw(faiss)
```

fix docker tag for Faiss HNSW

---

ann_benchmarks/definitions.py

Maybe I'm missing something, but it seems like the logic in `_get_algorithm_definitions` leads to incorrectly skipping algorithm definitions, which I've attempted to fix here.
For example, elastiknn has definitions for the "point types" `any` and `euclidean`: https://github.com/erikbern/ann-benchmarks/blob/main/ann_benchmarks/algorithms/elastiknn/config.yml
But, if I run `python run.py --algorithm elastiknn-l2lsh --dataset random-xs-20-euclidean --run-disabled --timeout 30 --local --force --runs 1`, I get the "Nothing to run" exception. That doesn't make sense IMO. Elastiknn has definitions for the `euclidean` point type, so there is not "nothing to run".
It seems that the non-any point type is skipped because of the logic in `_get_algorithm_definitions`. If an algorithm has definitions …

Fix logic in _get_algorithm_definitions to avoid skipping algorithm definitions

---

ann_benchmarks/definitions.py

`load_configs()` failed always because of ann_benchmarks/algorithms/base/config.yaml is empty.
`yaml.safe_load()` returns `None` for empty steam (https://pyyaml.org/wiki/PyYAMLDocumentation).
This fixes it with skipping `None` which returned from `yaml.safe_load()`

Skip loading base/config.yml on Windows.

---

ann_benchmarks/distance.py

Both `sift-256-hamming` and `word2bits-800-hamming` always report 0 recall, as the distances in the HDF5 files are floats between 0 and 1 rather than the Hamming distance. Multiplying by the dataset dimensions fixes it.
This issue is likely the cause of #420.

Fix recall for Hamming distance

---

ann_benchmarks/runner.py

When an error is reported, container.logs() returns an iterator over lines of bytes. The decode() function should apply to each line, not to the iterator, otherwise we get no logs, but an error message saying there is no decode() function in the iterator.
This change follows the same pattern as stream_logs() in the same file.

fix error reporting of runner

---

test/distance_test.py

This PR updates the test_hamming function in our pytest suite to correctly reflect the normalized Hamming distance. The previous test was expecting a raw Hamming distance of 2, but since our metric function calculates the normalized Hamming distance, the expected value should be 0.5.
```python
"hamming": Metric(
distance=lambda a, b: np.mean(a.astype(np.bool_) ^ b.astype(np.bool_)),
distance_valid=lambda a: True
),
```
Updated the expected values in test_hamming from 2 to 0.5 to align with the normalized Hamming distance calculation.
Reasoning:
The metrics["hamming"].distance function calculates the normalized Hamming distance by taking the mean of the boolean XOR results. Thus, for arrays p and q given in the tests:
p = [1, 1, 0, 0]
q = [1, 0, 0, 1]
The raw Hamming distance is 2 (two …

Fix Hamming distance test to reflect normalized values

---

ann_benchmarks/definitions.py
ann_benchmarks/main.py

Hi! Great benchmark that you have here.
I noticed that the value of the `--definitions` argument is only used when listing all available algorithms. Correct me if I'm wrong, but I wanted to pass my own algorithm configurations, which are stored elsewhere, by using `--definitions`. This doesn't work because the program uses the default path `ann-benchmarks/algorithms`.

Use custom definitions for algorithms

---

.github/workflows/benchmarks.yml
README.md
ann_benchmarks/algorithms/expann/Dockerfile
ann_benchmarks/algorithms/expann/config.yml
ann_benchmarks/algorithms/expann/module.py

Hello! Nice benchmarking repo.
[ExpANN](https://github.com/jacketsj/expANN/) has been my personal dev repo for in-memory ANN experiments for quite some time now. One of the engines had enough performance to dominate all the rest, so all the others were eventually pruned and now it's just a single implementation. This PR runs this engine in ann-benchmarks.
The engine is a fast graph-based search implementation that incorporates various aspects of a bunch of different graph-based search papers, and a number of small novel ideas.
I wrote it entirely on my own, but it's quite fast. As a single data point for baseline: On my own machine (probably faster than an aws r6i.16xlarge for single-threaded performance), I've been able to hit 96% recall at 22.4k QPS on SIFT-1M. That also included a …

Add expann

---

.github/workflows/benchmarks.yml
ann_benchmarks/algorithms/parlayann/Dockerfile
ann_benchmarks/algorithms/parlayann/config.yml
ann_benchmarks/algorithms/parlayann/module.py

ParlayANN implements a variety of algorithms as described in the paper: https://dl.acm.org/doi/10.1145/3627535.3638475  This pull request uses the ParlayANN version of Vamana (with some significant changes from the original).  It was designed for large data sets and high parallelism, but works well on smaller graphs and a single thread.
It does not use any product quantization, but does use scalar quantization, and for large dimensions (just GIST is large enough for this suite) uses  the Johnson-Lindenstrauss transform to reduce dimensionality.

Add ParlayANN to ann-benchmarks

---

ann_benchmarks/algorithms/elastiknn/Dockerfile
ann_benchmarks/algorithms/elastiknn/config.yml
requirements.txt

This also includes the change from #543, which was necessary to get this to run.

Update Elastiknn to latest release and latest benchmark parameters

---

.github/workflows/benchmarks.yml
ann_benchmarks/algorithms/vsag/Dockerfile
ann_benchmarks/algorithms/vsag/config.yml
ann_benchmarks/algorithms/vsag/module.py
ann_benchmarks/main.py

add vsag library, and also fixes: #547

add vsag library

---

ann_benchmarks/algorithms/hnswlib/module.py

When exporting the CSV results of hnswlib, the parameters in the file do not include the ef value from the query arguments. This pull request modifies self.name to include it, facilitating performance comparison.

Modify the string of hnswlib's parameters to add efQuery

---

ann_benchmarks/algorithms/pgvector/module.py
ann_benchmarks/definitions.py
ann_benchmarks/util.py

- Allow specifying PostgreSQL credentials when running against an external instance of PostgreSQL not managed by the benchmark. 
- Allow avoiding an attempt to start PostgreSQL service with systemctl, because it might be managed in a different way. 
- Create the `vector` PostgreSQL extension automatically if it does not exist.
Fixes: #563

Add ability to specify Postgres connection credentials

---

.github/workflows/benchmarks.yml
README.md
ann_benchmarks/algorithms/pgvectorscale/Dockerfile
ann_benchmarks/algorithms/pgvectorscale/config.yml
ann_benchmarks/algorithms/pgvectorscale/module.py

This commit inspired by timescale blog post publication [1] about performance improvements over current implementation of the pgvector [2] implementation. Adding a benchmark to evaluate implementation suggested by PgVectorScale project.
[1]: https://www.timescale.com/blog/pgvector-is-now-as-fast-as-pinecone-at-75-less-cost/
[2]: https://github.com/timescale/pgvectorscale/tree/main

Add pgvectorscale
